# NUMPY
# Question 01

In [1]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

addition_result = array1 + array2
print("Addition:\n", addition_result)

Addition:
 [ 6  8 10 12]


In [2]:
subtraction_result = array1 - array2

print("Subtraction:\n", subtraction_result)

Subtraction:
 [-4 -4 -4 -4]


In [3]:
multiplication_result = array1 * array2

print("Multiplication:\n", multiplication_result)

Multiplication:
 [ 5 12 21 32]


In [4]:
division_result = array1 / array2

print("Division:\n", division_result)

Division:
 [0.2        0.33333333 0.42857143 0.5       ]


# Question 02

In [5]:
array_1d = np.array([10, 20, 30, 40, 50])

array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])


# Indexing
element_1d = array_1d[2]
print(element_1d)

element_2d = array_2d[1, 2]
print(element_2d)

30
6


In [6]:
# Slicing
slice_1d = array_1d[1:3]
print(slice_1d)

slice_2d = array_2d[0:2, 0:2]
print(slice_2d)

[20 30]
[[1 2]
 [4 5]]


# Question 03

In [7]:
array_1d = np.arange(12)

print("Original 1D array:\n", array_1d)

Original 1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [8]:
array_2d = array_1d.reshape(3, 4)

print("Reshaped to 2D array (3x4):\n", array_2d)

Reshaped to 2D array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
array_3d = array_1d.reshape(2, 3, 2)

print("Reshaped to 3D array (2x3x2):\n", array_3d)

Reshaped to 3D array (2x3x2):
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [10]:
transposed_array = array_2d.T

print("Transposed 2D array:\n", transposed_array)

Transposed 2D array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# Question 04

In [11]:
data = np.array([10, 20, 30, 40, 50])

mean_value = np.mean(data)
print("Mean:", mean_value)

Mean: 30.0


In [12]:
median_value = np.median(data)
print("Median:", median_value)

Median: 30.0


In [13]:
std_deviation = np.std(data)
print("Standard Deviation:", std_deviation)

Standard Deviation: 14.142135623730951


In [14]:
variance_value = np.var(data)
print("Variance:", variance_value)

Variance: 200.0


# Question 05

In [15]:
int_array = np.array([1, 2, 3, 4, 5], dtype=int)

print(int_array)

[1 2 3 4 5]


In [16]:
float_array = np.array([1.0, 2.5, 3.7, 4.8], dtype=float)

print(float_array)

[1.  2.5 3.7 4.8]


In [17]:
bool_array = np.array([True, False, True, False], dtype=bool)

print(bool_array)

[ True False  True False]


In [18]:
str_array = np.array(["apple", "banana", "cherry"], dtype=str)

print(str_array)

['apple' 'banana' 'cherry']


# Question 06

In [19]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

array3 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array4 = np.array([[7, 8, 9],
                   [10, 11, 12]])

In [20]:
concatenated_1d = np.concatenate((array1, array2))

print(concatenated_1d)

[1 2 3 4 5 6]


In [21]:
concatenated_vertical = np.concatenate((array3, array4), axis=0)

print(concatenated_vertical)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
concatenated_horizontal = np.concatenate((array3, array4), axis=1)

print(concatenated_horizontal)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# Question 07

In [23]:
array = np.array([5, 2, 9, 1, 5, 6])

print("Original Array:", array)

Original Array: [5 2 9 1 5 6]


In [24]:
sorted_array_asc = np.sort(array)

print("Sorted Array (Ascending):", sorted_array_asc)

Sorted Array (Ascending): [1 2 5 5 6 9]


In [25]:
sorted_array_desc = np.sort(array)[::-1]

print("Sorted Array (Descending):", sorted_array_desc)

Sorted Array (Descending): [9 6 5 5 2 1]


In [26]:
array_2d = np.array([[5, 2, 9],
                     [1, 5, 6]])
sorted_2d_rows = np.sort(array_2d, axis=1)

print("Sorted 2D Array (Rows):\n", sorted_2d_rows)

Sorted 2D Array (Rows):
 [[2 5 9]
 [1 5 6]]


In [27]:
sorted_2d_cols = np.sort(array_2d, axis=0)

print("Sorted 2D Array (Columns):\n", sorted_2d_cols)

Sorted 2D Array (Columns):
 [[1 2 6]
 [5 5 9]]


# PANDAS
# Question 01

In [1]:
import pandas as pd

df = pd.read_csv('retail supermarket.csv')
df

Ship Mode    Segment        Country             City       State  \
0       Second Class   Consumer  United States        Henderson    Kentucky   
1       Second Class   Consumer  United States        Henderson    Kentucky   
2       Second Class  Corporate  United States      Los Angeles  California   
3     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
...              ...        ...            ...              ...         ...   
9989    Second Class   Consumer  United States            Miami     Florida   
9990  Standard Class   Consumer  United States       Costa Mesa  California   
9991  Standard Class   Consumer  United States       Costa Mesa  California   
9992  Standard Class   Consumer  United States       Costa Mesa  California   
9993    Second Class   Consumer  United States      Westminster  California   

      Postal Code Region         Category Sub-Category     Sales  Quantity  \
0           42420  South        Furniture    Bookcases  261.9600         2   
1           42420  South        Furniture       Chairs  731.9400         3   
2           90036   West  Office Supplies       Labels   14.6200         2   
3           33311  South        Furniture       Tables  957.5775         5   
4           33311  South  Office Supplies      Storage   22.3680         2   
...           ...    ...              ...          ...       ...       ...   
9989        33180  South        Furniture  Furnishings   25.2480         3   
9990        92627   West        Furniture  Furnishings   91.9600         2   
9991        92627   West       Technology       Phones  258.5760         2   
9992        92627   West  Office Supplies        Paper   29.6000         4   
9993        92683   West  Office Supplies   Appliances  243.1600         2   

      Discount    Profit  
0         0.00   41.9136  
1         0.00  219.5820  
2         0.00    6.8714  
3         0.45 -383.0310  
4         0.20    2.5164  
...        ...       ...  
9989      0.20    4.1028  
9990      0.00   15.6332  
9991      0.20   19.3932  
9992      0.00   13.3200  
9993      0.00   72.9480  

[9994 rows x 13 columns]

# Question 02

In [2]:
print(df.shape)

(9994, 13)


In [3]:
print(df.dtypes)

Ship Mode        object
Segment          object
Country          object
City             object
State            object
Postal Code       int64
Region           object
Category         object
Sub-Category     object
Sales           float64
Quantity          int64
Discount        float64
Profit          float64
dtype: object


In [4]:
print(df.isnull().sum())

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64


# Question 03

In [6]:
df = pd.read_csv('retail supermarket.csv')

summary = df.describe()
print(summary)

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000


# Question 04

In [8]:
rows = df.iloc[:5]
print(rows)

        Ship Mode    Segment        Country             City       State  \
0    Second Class   Consumer  United States        Henderson    Kentucky   
1    Second Class   Consumer  United States        Henderson    Kentucky   
2    Second Class  Corporate  United States      Los Angeles  California   
3  Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4  Standard Class   Consumer  United States  Fort Lauderdale     Florida   

   Postal Code Region         Category Sub-Category     Sales  Quantity  \
0        42420  South        Furniture    Bookcases  261.9600         2   
1        42420  South        Furniture       Chairs  731.9400         3   
2        90036   West  Office Supplies       Labels   14.6200         2   
3        33311  South        Furniture       Tables  957.5775         5   
4        33311  South  Office Supplies      Storage   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.871